import type { CatalogGame } from "~/modules/catalog/model";

// IDs match RAWG so local entries can also be refreshed with the live catalog.
export const demoCatalogGames: ReadonlyArray<CatalogGame> = [
  {
    id: "274755",
    title: "Hades",
    slug: "hades-2018",
    coverUrl: "/demo-covers/hades.svg",
    releaseDate: "2020-09-17",
    genres: ["Action", "Roguelike"],
    developers: ["Supergiant Games"],
    publishers: ["Supergiant Games"],
  },
  {
    id: "22121",
    title: "Celeste",
    slug: "celeste",
    coverUrl: "/demo-covers/celeste.svg",
    releaseDate: "2018-01-25",
    genres: ["Platformer"],
    developers: ["Maddy Makes Games"],
    publishers: ["Maddy Makes Games"],
  },
  {
    id: "3328",
    title: "The Witcher 3: Wild Hunt",
    slug: "the-witcher-3-wild-hunt",
    coverUrl: "/demo-covers/the-witcher-3-wild-hunt.svg",
    releaseDate: "2015-05-18",
    genres: ["RPG"],
    developers: ["CD Projekt RED"],
    publishers: ["CD Projekt"],
  },
  {
    id: "9767",
    title: "Hollow Knight",
    slug: "hollow-knight",
    coverUrl: "/demo-covers/hollow-knight.svg",
    releaseDate: "2017-02-24",
    genres: ["Action", "Platformer"],
    developers: ["Team Cherry"],
    publishers: ["Team Cherry"],
  },
  {
    id: "28",
    title: "Red Dead Redemption 2",
    slug: "red-dead-redemption-2",
    coverUrl: "/demo-covers/red-dead-redemption-2.svg",
    releaseDate: "2018-10-26",
    genres: ["Action", "Adventure"],
    developers: ["Rockstar Games"],
    publishers: ["Rockstar Games"],
  },
  {
    id: "654",
    title: "Stardew Valley",
    slug: "stardew-valley",
    coverUrl: "/demo-covers/stardew-valley.svg",
    releaseDate: "2016-02-25",
    genres: ["RPG", "Simulation", "Indie"],
    developers: ["Chucklefish", "ConcernedApe"],
    publishers: ["Chucklefish", "ConcernedApe"],
  },
  {
    id: "13536",
    title: "Portal",
    slug: "portal",
    coverUrl: "/demo-covers/portal.svg",
    releaseDate: "2007-10-09",
    genres: ["Action", "Puzzle"],
    developers: ["Valve Software", "NVIDIA Lightspeed Studios"],
    publishers: ["Valve", "Buka Entertainment", "NVIDIA", "CyberFront"],
  },
  {
    id: "4200",
    title: "Portal 2",
    slug: "portal-2",
    coverUrl: "/demo-covers/portal-2.svg",
    releaseDate: "2011-04-18",
    genres: ["Shooter", "Puzzle"],
    developers: ["Valve Software"],
    publishers: ["Electronic Arts", "Valve"],
  },
  {
    id: "326243",
    title: "Elden Ring",
    slug: "elden-ring",
    coverUrl: "/demo-covers/elden-ring.svg",
    releaseDate: "2022-02-25",
    genres: ["Action", "RPG"],
    developers: ["FromSoftware"],
    publishers: ["Bandai Namco Entertainment", "FromSoftware"],
  },
  {
    id: "324997",
    title: "Baldur's Gate III",
    slug: "baldurs-gate-3",
    coverUrl: "/demo-covers/baldurs-gate-3.svg",
    releaseDate: "2023-08-03",
    genres: ["Adventure", "RPG", "Strategy"],
    developers: ["Larian Studios"],
    publishers: ["Larian Studios"],
  },
  {
    id: "262382",
    title: "Disco Elysium",
    slug: "disco-elysium",
    coverUrl: "/demo-covers/disco-elysium.svg",
    releaseDate: "2019-10-14",
    genres: ["Adventure", "RPG", "Indie"],
    developers: ["ZA/UM"],
    publishers: [],
  },
  {
    id: "41494",
    title: "Cyberpunk 2077",
    slug: "cyberpunk-2077",
    coverUrl: "/demo-covers/cyberpunk-2077.svg",
    releaseDate: "2020-12-10",
    genres: ["Action", "Shooter", "RPG"],
    developers: ["CD PROJEKT RED", "CD PROJEKT"],
    publishers: ["CD PROJEKT RED"],
  },
  {
    id: "5679",
    title: "The Elder Scrolls V: Skyrim",
    slug: "the-elder-scrolls-v-skyrim",
    coverUrl: "/demo-covers/the-elder-scrolls-v-skyrim.svg",
    releaseDate: "2011-11-11",
    genres: ["Action", "RPG"],
    developers: ["Bethesda Game Studios"],
    publishers: ["Bethesda Softworks"],
  },
  {
    id: "2551",
    title: "Dark Souls III",
    slug: "dark-souls-iii",
    coverUrl: "/demo-covers/dark-souls-iii.svg",
    releaseDate: "2016-04-11",
    genres: ["Action", "RPG"],
    developers: ["BANDAI NAMCO Entertainment America", "FromSoftware"],
    publishers: [
      "Bandai Namco Entertainment",
      "BANDAI NAMCO Entertainment US",
      "FromSoftware",
    ],
  },
  {
    id: "50734",
    title: "Sekiro: Shadows Die Twice",
    slug: "shadows-die-twice",
    coverUrl: "/demo-covers/shadows-die-twice.svg",
    releaseDate: "2019-03-22",
    genres: ["Action", "RPG"],
    developers: ["FromSoftware"],
    publishers: ["FromSoftware", "Activision Value Publishing", "方块游戏"],
  },
  {
    id: "58764",
    title: "Outer Wilds",
    slug: "outer-wilds",
    coverUrl: "/demo-covers/outer-wilds.svg",
    releaseDate: "2019-05-29",
    genres: ["Adventure", "Indie", "Puzzle"],
    developers: ["Mobius Digital"],
    publishers: ["Annapurna Interactive"],
  },
  {
    id: "13627",
    title: "Undertale",
    slug: "undertale",
    coverUrl: "/demo-covers/undertale.svg",
    releaseDate: "2015-09-14",
    genres: ["RPG", "Indie"],
    developers: ["8-4", "Toby Fox"],
    publishers: ["8-4", "Toby Fox"],
  },
  {
    id: "11726",
    title: "Dead Cells",
    slug: "dead-cells",
    coverUrl: "/demo-covers/dead-cells.svg",
    releaseDate: "2018-08-07",
    genres: ["Action", "RPG", "Indie", "Platformer"],
    developers: ["Plug In Digital", "Playdigious", "Motion Twin"],
    publishers: ["Plug In Digital", "Playdigious", "Motion Twin"],
  },
  {
    id: "28121",
    title: "Slay the Spire",
    slug: "slay-the-spire",
    coverUrl: "/demo-covers/slay-the-spire.svg",
    releaseDate: "2019-01-22",
    genres: ["RPG", "Strategy", "Card", "Indie"],
    developers: ["Humble Bundle", "Mega Crit"],
    publishers: ["Humble Bundle", "Mega Crit Games"],
  },
  {
    id: "422",
    title: "Terraria",
    slug: "terraria",
    coverUrl: "/demo-covers/terraria.svg",
    releaseDate: "2011-05-16",
    genres: ["Action", "Indie", "Platformer"],
    developers: ["Engine Software", "Codeglue", "Pipeworks Studio", "Re-Logic"],
    publishers: ["505 Games", "Headup Games", "Spike Chunsoft", "Re-Logic"],
  },
];
